# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  IISWebSite: 'tfsutils'

resources:
 pipelines:
     - pipeline: 'buildPipeline'  
       source: 'Build pipeline'
       branch: 'main'
       version: '20230519.4'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'TFSViewer.VM-ALEXEYD-10'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'buildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'TFSViewerArtifacts'
                