# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
  - stage: main
    displayName: "main"
    jobs:
      - job: build
        steps:
        - task: UseDotNet@2
          displayName: 'Use Dot Net'
          inputs:
            version: '7.x'
          
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/*.csproj'

      - deployment: MainDeploy
        displayName: 'Main deploy'
        environment: 
         name: TFSViewer
         resourceName: VM-ALEXEYD-10
         resourceType: virtualMachine

         





