# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  IISWebSite: 'tfsutils'

resources:
 pipelines:
     - pipeline: 'buildPipeline'  
       source: 'Build pipeline'
       branch: 'main'
       version: Latest
      
      
stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'TFSViewer.VM-ALEXEYD-10'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'buildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'TFSViewerArtifacts'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'
                    
                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  inputs:
                      WebSiteName: '${{ variables.IISWebsiteName }}'
                      Package: '$(Pipeline.Workspace)\buildPipeline\TFSViewerArtifacts\TFSViewer'
                      TakeAppOfflineFlag: true
                  
                -task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS website'                     
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'