# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml




trigger:
- master

pool:
  vmImage: windows-latest
  
variables:
  project: '**/TFSViewer.csproj'
  IISWebSite: 'default web site'

stages:
  - stage: build
    jobs:
    - job: test
      steps:
        - checkout: none
          path: 'repo'

        - script: echo 'Pipeline.Workspace = $(Pipeline.Workspace)'

        - script: echo '$(System.DefaultWorkingDirectory)'
